name: Luacheck

on: [push, pull_request]

jobs:
  luacheck:
    runs-on: ubuntu-latest

    steps:    
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: 5.3
    - name: Create Environment Variables
      run: |
        LUA="lua=5.1"
    - name: Setup dependencies
      run: |
        luarocks install luafilesystem
        luarocks install busted
        luarocks install luacheck
    - name: Run Code Linter
      run: |
        luacheck src
